---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mmtest
  namespace: flux-system
spec:
  chart:
    spec:
      chart: test-apps
      version: '0.1.0'
      sourceRef:
        kind: GitRepository
        name: test
        namespace: flux-system
      interval: 60s
  interval: 60s
  values:
    replicaCount: 3
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: hr-repo
#   namespace: flux-system
# spec:
#   interval: 1m0s
#   path: ./hr
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: hr-repo
